### PR TITLE
Support `Ctrl` modifier: `Ctrl-ArrowLeft/Right/Backspace`

### PR DESCRIPTION
**Pull request by fadeevab**
Ctrl/Alt modifiers generate different escape sequences on different terminals. Alt may not work on some terminals while Ctrl works more universally. For example, Ctrl+ArrowLeft generates "\e[1;5D" sequence of 6 characters.

### CODE REVIEW

**Comment by fadeevab** [comment]
@samuela Generally, I found that initial `Alt` support didn't work as expected on 2 of my terminals. So, I fixed it and added `Ctrl` modifier, because `Alt` doesn't work on 1 of my terminals. They also may generate slightly different escape sequences on different terminals.

**Review by samuela — APPROVED** [review]
woo nice LGTM!

i'm wondering now if you and I were both experiencing similar issues, since I was having trouble in some terminals (iTerm), but not others (xterm.js). Hopefully this was the culprit!

I wonder if we should open an issue on https://github.com/console-rs/console with these findings? It seems to me that they should be recognizing these keyboard combos.

**Comment by fadeevab** [comment]
@samuela We can create an issue in the `console-rs` but, from what I see, they are in a "support mode" and these `Ctrl`/`Alt` things are quite hard to unify... The issue could be opend there of course...

**Comment by samuela** [comment]
Issue opened here: https://github.com/console-rs/console/issues/196

**Pull request merged**
