### PR TITLE
feat: 🚧 Working on skippable selects

### LINKED ISSUE #78: [improvement] add `required()` to `Select<T>`
Sometimes, in some selection, perhaps you may not want select anything because you are in a skippable step.

for example I am writing a CLI tool to write commits in an easy way and some steps are skippable like this:
image

Maybe you don't have a scope or you don't want to set any scope. Maybe these days I'll do a PR to add this.

### PR DESCRIPTION
**Pull request by romancitodev**
Closes #78

### CODE REVIEW

**Comment by romancitodev** [comment]
At this point, the “skip” works fine, in the `examples/select.rs` can be checked, but I am looking for where actually some messages are rendered.

**Comment by romancitodev** [comment]
@fadeevab Well, I changed the API with the approach I told you about to make `Select<T>` use types to control how it will render.

**Comment by romancitodev** [comment]
The last thing I still need to figure out is where in the rendering the text is stretched, because when I press enter, the state is sent and the text becomes opaque and when I press Tab (the key I set up to skip the choosing process) it does the same thing.

**Comment by fadeevab** [comment]
> The last thing I still need to figure out is where in the rendering the text is styled

@romancitodev It's literally what I'd like to see first ;) I believe you come from the code's side of things. If the user experience becomes more tricky at the UI part, the patch will most likely be postponed.

**Pull request closed without merging**
