### PR TITLE
Re-implemented `spinner` through the `ProgressBar`

### PR DESCRIPTION
**Pull request by fadeevab**
* Incompatible API change: `spinner()` returns the `ProgressBar` the methods of which are not `mut`.
* `with_download_template`, `with_spinner_temple`, `with_template(custom)`
* Spinner can be used in a multi-progress bar.
* `MultiBar::`: `stop`, `cancel`, `error(msg)`.

image

### CODE REVIEW

**Comment by fadeevab** [comment]
@cylewitruk Review

**Comment by fadeevab** [comment]
@cylewitruk FYI, I can't use the `as_` prefix because of the linter complaints. `as_` is a specific idiomatic prefix where `&self` should be a reference. Thus, `with_download_template` which is more explicit basically.

**Review by cylewitruk — APPROVED** [review]
Looks awesome! :smile: 

I really like what's happened with the spinner in general, feels like these `indicatif` things are more "packaged up".

**Comment by cylewitruk** [comment]
> @cylewitruk FYI, I can't use the `as_` prefix because of the linter complaints. `as_` is a specific idiomatic prefix where `&self` should be a reference. Thus, `with_download_template`, which is more explicit.

Ah, no big deal, `with` works just as well :)

**Pull request merged**
