### PR TITLE
Improve `note` widget rendering considering colors and emojis display width

### PR DESCRIPTION
**Pull request by fadeevab**
Issue #12: cliclack::note does not correctly calculate text width when handling ANSI escape codes and emojis

### CODE REVIEW

**Comment by fadeevab** [comment]
@samuela Please, review

**Comment by fadeevab** [comment]
Color + emoji (width handled correctly):
image

@samuela FYI

**Review by samuela — APPROVED** [review]
Niceee, looks great! Diff LGTM

> I made the note example a bit complicated for testing (emoji + colors), however, I'm not sure it's necessary as it may look overcomplicated for beginners. WDYT?

Perhaps this could be used as an opportunity to showcase cliclack's abilities in the example? Eg the note could be something like "hey, look how well cliclack can handle < red >colors</ red > and emojis 💯 "

IMHO I wouldn't find that to be overly complex for example code

**Comment by fadeevab** [comment]
@samuela Thanks, buddy!

**Pull request merged**
