### PR TITLE
Use 1 space gap inside of the multi-progress bars

### PR DESCRIPTION
**Pull request by fadeevab**

### CODE REVIEW

**Review by cylewitruk — APPROVED** [review]
lgtm :) yeah two spaces look fine as well, it's just that the default spacing for other states is only one space, so it ends up being unaligned :shrug:  Looked weird to me anyway :)

**Comment by fadeevab** [comment]
@cylewitruk could you please re-test the `main` branch on your code? I rearranged a code a little bit to avoid the "line jumping while terminal resizing" issue.

**Comment by fadeevab** [comment]
@cylewitruk "green-unfilled" is the success symbol from the main theme of the original JS `@clack/prompts`, and I'd like to keep it consistent.

**Comment by fadeevab** [comment]
@cylewitruk I enabled https://github.com/fadeevab/cliclack/discussions

**Pull request merged**
